[package]
name = "new_york_calculate_core"
version = "0.0.56"
authors = ["Andrey Makarov <viva.la.akam@gmail.com>"]
edition = "2018"
description = "Library for calculation some things"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7"
log = "0.4"
serde_json = "1.0"
env_logger = "0.10"
new_york_utils = "0.1"
tokio = { version = "1.19", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }

[lib]
name = "new_york_calculate_core"
