[package]
name = "new_york_calculate_core"
version = "0.0.11"
authors = ["Andrey Makarov <viva.la.akam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7"
log = "0.4"

[lib]
name = "new_york_calculate_core"
