[package]
name = "new_york_calculate"
version = "0.0.56"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "new_york_calculate"
crate-type = ["staticlib"]

[dependencies]
