name: Build nodejs package app

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.11
    strategy:
      matrix:
        os: [windows-2019, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: ./node
        run: |
          npm install

      - name: Build
        working-directory: ./node
        run: |
          npm run build

      - name: Publish artefacts
        working-directory: ./node
        run: |
          npm run package 
          npm run publish:package
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{secrets.NODE_PRE_GYP_GITHUB_TOKEN}}

  build-js:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        working-directory: ./node
        run: |
          npm install

      - name: Build js
        working-directory: ./node
        run: |
          npm run build-js

      - name: Publish
        run: npm publish
        working-directory: ./node
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
