name: Build python package app

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, ubuntu-18.04]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        pip install numpy
        pip install maturin

    - name: Build
      working-directory: ./python
      run: |
        maturin build

    - name: Release
      working-directory: ./python
      run: |
        maturin publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
